version: 2
updates:
  - package-ecosystem: "docker"
    directory: ".devcontainer/"
    schedule:
      interval: "weekly"
      time: "21:00"
      timezone: "America/New_York"
    reviewers:
      - "exilesprx"
